---
title: "Playoff 2 Messy Work"
author: "Weston Murdock"
date: "2023-04-01"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(readr) # Data Reading
library(car) # VIF Calculation
library(Stat2Data) # Textbook
library(leaps) # Model Selection
library(corrplot) # Correlation Plot
library(polynom) # Polynomial Models
library(bestglm) # Logistic Regression Model Selection
library(MASS) # Better Logistic Regression Model Selection
library(dplyr) # Piping Syntax
library(gmodels) # Contrasts
library(ggplot2) # Visualizations
library(data.table)
library(zoo)
library(nbastatR)

logit = function(B0, B1, x)
{
  exp(B0+B1*x)/(1+exp(B0+B1*x))
}

Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)
```


```{r}
temp = list.files("/Users/wlm0921/Documents/Current Courses/STOR 538/Playoff 2/CSV Files/", pattern="*.csv")
setwd("/Users/wlm0921/Documents/Current Courses/STOR 538/Playoff 2/CSV Files/")
for (i in 1:length(temp)) {
  assign(substr(temp[i], 1, nchar(temp[i]) - 4), read.csv(temp[i]))
}
```


```{r}
games_details = read_csv("GAMES_DETAILS_H_W.csv")
bad_ids = read_csv("BAD_IDs.csv")
```


```{r}
unique_ids = unique(games_details$PLAYER_ID)
bad_ids = data.frame()
length(unique_ids)
```


```{r}
test_id = 1626158
test_player_pm = games_details$PLUS_MINUS[which(games_details$PLAYER_ID == test_id)]
if (length(test_player_pm[which(!is.na(test_player_pm))])) {
  length(test_player_pm[which(!is.na(test_player_pm))])
}
```


```{r}
write_csv(games_details, "GAMES_DETAILS_H_W.csv")
write_csv(bad_ids, "BAD_IDs.csv")
```


```{r}
write_csv(games_details[1:334314,], "GAMES_DETAILS_H_W_1.csv")
write_csv(games_details[334315:668628,], "GAMES_DETAILS_H_W_2.csv")
```


```{r}
length(games_details$HEIGHT[which(is.na(games_details$HEIGHT))])
# games_details$PLAYER_ID[which(games_details$PLAYER_NAME == "Jerry Stackhouse")]
# bad_ids = bad_ids %>% distinct()
nrow(games_details[,1])
```


```{r}
indices = 603:650
for (id in unique_ids[indices]) {
  player_pm = games_details$PLUS_MINUS[which(games_details$PLAYER_ID == id)]
  if ((length(player_pm[which(!is.na(player_pm))]) > 0 ) & (id != 1627758) & (id != 711)) {
    tryCatch({
      profile = player_profiles(player_ids = id, return_message = FALSE)
      which_indices = which(games_details$PLAYER_ID == id)
      games_details$HEIGHT[which_indices] = profile$heightInches
      games_details$WEIGHT[which_indices] = profile$weightLBS
    }, error = function(a) {
      bad_ids <<- rbind(bad_ids, data.frame(bad_ids = id))
    }
    )
  }
}
```













```{r}
cor(AtlantaHawks23[, colnames(AtlantaHawks23) != "OREB"] %>% select_if(is.numeric), AtlantaHawks23$OREB)
```


```{r}
AtlantaHawks23$rolling_avg <- rollapply(AtlantaHawks23$FGA, width = list(-11:-2), FUN = mean, align = "right", fill = NA, partial=TRUE)
```


```{r}
mean(AtlantaHawks23$FGA[1:10])
-10:-1
```

```{r}
AtlantaHawks23$FGA_PCT = (1 - AtlantaHawks23$FG_PCT) * AtlantaHawks23$FGA
cor(AtlantaHawks23$FGA_PCT, AtlantaHawks23$OREB)
```

```{r}
cor(AtlantaHawks23[complete.cases(AtlantaHawks23),]$rolling_avg, AtlantaHawks23[complete.cases(AtlantaHawks23),]$OREB)
```

```{r}
correlations = data.frame()

for (N in 1:20) {
  FGA_AVG = rollapply(AtlantaHawks23$FGA, width = list(-(N+1):-2), FUN = mean, align = "right", fill = NA, partial=TRUE)
  next_row = data.frame(N = N, COR = cor(FGA_AVG[complete.cases(FGA_AVG)], AtlantaHawks23[complete.cases(FGA_AVG),]$OREB))
  correlations = rbind(correlations, next_row)
}

correlations

plot(correlations$N, correlations$COR)
```


```{r}
hist(ALLNBAGames$PTS_away + ALLNBAGames$PTS_home, breaks = 30)
```


```{r message=FALSE}
suppressWarnings(player_profiles(player_ids = 203500, return_message=FALSE)$weightLBS)
suppressWarnings(player_profiles(player_ids = 203500, return_message=FALSE)$heightInches)

# DFNAME$PlayerHeight = suppressWarnings(player_profiles(player_ids = DFNAME$PlayerID, return_message=FALSE)$heightInches)
# DFNAME$PlayerWeight = suppressWarnings(player_profiles(player_ids = DFNAME$PlayerID, return_message=FALSE)$weightLBS)
```


```{r}
length(unique(ALLNBAGames$Game_ID))
length(unique(games_details$GAME_ID))
length(intersect(unique(games_details$GAME_ID), unique(ALLNBAGames$Game_ID)))
intersection = intersect(unique(games_details$GAME_ID), unique(ALLNBAGames$Game_ID))
head(intersection)
```


```{r}
test_game_frame = games_details[which(games_details$GAME_ID == 22200477),]
test_game_frame
```


```{r}
test_game_frame2 = ALLNBAGames[which(ALLNBAGames$Game_ID == 22200477),]
test_game_frame2
```


```{r echo=TRUE, results='hide'}
test_heights = player_profiles(player_ids=test_game_frame$PLAYER_ID)$heightInches
```


```{r}
test_heights
```


```{r}
player_profiles(player_ids=unique_ids[1], return_message=FALSE)$heightInches
```


```{r}
games_details$PLAYER_ID[which(games_details$PLAYER_NAME == "Speedy Claxton")]
```

```{r}
which(unique_ids == 2049)
```



```{r}
test_id = data.frame()
id_is_bad = FALSE
tryCatch({
  profile = player_profiles(player_ids = id, return_message = FALSE)
  which_indices = which(games_details$PLAYER_ID == id)
  games_details$HEIGHT[which_indices] = profile$heightInches
  games_details$WEIGHT[which_indices] = profile$weightLBS
}, warning = function(e) {
  id_is_bad <<- TRUE
}, error = function(e) {
  id_is_bad <<- TRUE
}
)
if (id_is_bad) test_id = rbind(test_id, data.frame(bad_ids = id))

test_id
```


```{r}
length(which(games_details$HEIGHT == 77))
```

















